 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rate_cap_updates", type: :request do
  # RateCapUpdate. As you add validations to RateCapUpdate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RateCapUpdate.create! valid_attributes
      get rate_cap_updates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rate_cap_update = RateCapUpdate.create! valid_attributes
      get rate_cap_update_url(rate_cap_update)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rate_cap_update_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rate_cap_update = RateCapUpdate.create! valid_attributes
      get edit_rate_cap_update_url(rate_cap_update)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RateCapUpdate" do
        expect {
          post rate_cap_updates_url, params: { rate_cap_update: valid_attributes }
        }.to change(RateCapUpdate, :count).by(1)
      end

      it "redirects to the created rate_cap_update" do
        post rate_cap_updates_url, params: { rate_cap_update: valid_attributes }
        expect(response).to redirect_to(rate_cap_update_url(RateCapUpdate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RateCapUpdate" do
        expect {
          post rate_cap_updates_url, params: { rate_cap_update: invalid_attributes }
        }.to change(RateCapUpdate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rate_cap_updates_url, params: { rate_cap_update: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rate_cap_update" do
        rate_cap_update = RateCapUpdate.create! valid_attributes
        patch rate_cap_update_url(rate_cap_update), params: { rate_cap_update: new_attributes }
        rate_cap_update.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rate_cap_update" do
        rate_cap_update = RateCapUpdate.create! valid_attributes
        patch rate_cap_update_url(rate_cap_update), params: { rate_cap_update: new_attributes }
        rate_cap_update.reload
        expect(response).to redirect_to(rate_cap_update_url(rate_cap_update))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rate_cap_update = RateCapUpdate.create! valid_attributes
        patch rate_cap_update_url(rate_cap_update), params: { rate_cap_update: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rate_cap_update" do
      rate_cap_update = RateCapUpdate.create! valid_attributes
      expect {
        delete rate_cap_update_url(rate_cap_update)
      }.to change(RateCapUpdate, :count).by(-1)
    end

    it "redirects to the rate_cap_updates list" do
      rate_cap_update = RateCapUpdate.create! valid_attributes
      delete rate_cap_update_url(rate_cap_update)
      expect(response).to redirect_to(rate_cap_updates_url)
    end
  end
end
