SIGNIO_API_URL: 'https://test01.legops.com/staging/signio/api/v2'
SIGNIO_ACCESS_KEY: '4$LoPI3U@3$tN1'
SIGNIO_EMAIL: 'api@lumni.com'
HTTP_AUTHORIZATION: 'LM.1f46+dc91ff8283dFNI.ca67151f70fe076021fedc0ceDFsdM'
EXTERNAL_CONSUMER_API: 'LM.1f46+dc91ff8283dFNI.ca67151f70fe076021fedc0ceDFsdM'
LEGAL_REPRESENTATIVE_EMAIL: 'robertorueda89@hotmail.com'
LEGAL_REPRESENTATIVE_IDENTIFICATION_NUMBER: '1045684650'
LEGAL_REPRESENTATIVE_IDENTIFICATION_TYPE: 'CC'
LEGAL_REPRESENTATIVE_MOBILE: '3176908727'
LEGAL_REPRESENTATIVE_NAME: 'Roberto Rueda'
LEGAL_REPRESENTATIVE_COMPANY_NAME: 'LUMNI Inc.'
LEGAL_REPRESENTATIVE_COMPANY_NIT: '8301451872'
ZIGMA_REPRESENTATIVE_EMAIL: 'roberto.rueda@lumni.net'
ZIGMA_REPRESENTATIVE_IDENTIFICATION_NUMBER: '1045684651'
ZIGMA_REPRESENTATIVE_IDENTIFICATION_TYPE: 'CC'
ZIGMA_REPRESENTATIVE_MOBILE: '3176908727'
ZIGMA_REPRESENTATIVE_NAME: 'Mario Quintero'
ZIGMA_REPRESENTATIVE_COMPANY_NAME: 'Fundacion Zigma'
ZIGMA_REPRESENTATIVE_COMPANY_NIT: '900199377'